version: "3.8"

services:
  web:
    build: .
    command: uvicorn main:app --reload --host
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres