version: "3.8"

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
        target: dev
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/upciti/
    environment:
      - FASTAPI_ENV=development
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres